<?php
    require_once "php/functions.php";

    session_start();

    $userstr = ' (Guest)';

// Check if user is signed in.
    if (isset($_SESSION['user']))
    {
        $user     = $_SESSION['user'];
        $loggedin = TRUE;
        $userstr  = " ($user)";
    }
    else $loggedin = FALSE;

// If the user is not signed in, they are redirected to the sign in/up form.
    if(!$loggedin)
    {
        header('Location: index.php');
    exit();
    }

// Handle form post.
    if(isset($_POST['name']) && isset($_POST['title']) && isset($_POST['text']))
    {
        // Sanitze inputs.
        $name = sanitizeString($db, $_POST['name']);
        $title = sanitizeString($db, $_POST['title']);
        $text = sanitizeString($db, $_POST['text']);

        // Name the file with current timestamp.
        $time = $_SERVER['REQUEST_TIME'];
    	$file_name = $time . '.jpg';

        // Get filter setting.
        if (isset($_POST['filter']))
        {
            $filter = $_POST['filter'];
        }
        else
        {
            $filter = "NULL";
        }

        // Get image file, upload to 'users' folder.
        if ($_FILES)
        {
            $tmp_name = $_FILES['upload']['name'];
            $dstFolder = 'users';
            move_uploaded_file($_FILES['upload']['tmp_name'], $dstFolder . DIRECTORY_SEPARATOR . $file_name);
        }

        // Input post data to table.
        SavePostToDB($db, $name, $title, $text, $time, $file_name, $filter);

        // Prevent duplicate submissions on page refresh.
        header("Location: wall.php");
        exit();
    }
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="COP3813 Homework 8 PHP Photo Sharing App Nick Petty">
    <meta name="author" content="Nick Petty">
    <link rel="icon" href="icons/favicon.ico">
<?php
    echo "    <title>$appname</title>\n";
?>
    <!-- CSS links. -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/jumbotron.css">
    <link rel="stylesheet" href="css/styles.css">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <!-- Navigation bar. -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
<?php
// Navbar buttons with user's name.
echo <<<_END
                <p class="navbar-text">$user
                    <a class="btn btn-lg btn-primary navbar-btn" href="logout.php" role="button">Sign out</a>
                    <a class="btn btn-lg btn-primary navbar-btn" href="form.php" role="button">Post pic</a>
                </p>
_END;
?>
            </div>
        </div>
    </nav>
    <!-- Photo wall, generated by php script and SQL queries. -->
    <div class="container">
        <?php echo getPostcards($db); ?>
    </div>
<?php $db->close(); ?>
    <!-- JavaScript placed at bottom for faster page loadtimes. -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>